[build-system]
requires = ["poetry-core~=2.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "trigger-s3-event"
version = "0.2.0"
description = ""
license = "Apache-2.0"
authors = [
  { name = "Rohan Weeden", email = "reweeden@alaska.edu" },
]
readme = "README.md"
requires-python = "~=3.9"
dependencies = [
  "boto3~=1.28",
  "dateparser~=1.2",
]

[tool.poetry]
packages = [{include = "trigger_s3_event"}]

[project.scripts]
trigger-s3-event = "trigger_s3_event:main.main"
s3event = "trigger_s3_event:main.main"

[tool.poetry.group.dev.dependencies]
moto = "~=5.0"
pytest = "~=8.3"
