[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "trigger-s3-event"
version = "0.1.2"
description = ""
authors = ["Rohan Weeden <reweeden@alaska.edu>"]
readme = "README.md"
packages = [{include = "trigger_s3_event"}]

[tool.poetry.scripts]
trigger-s3-event = "trigger_s3_event:main.main"
s3event = "trigger_s3_event:main.main"

[tool.poetry.dependencies]
python = ">=3.9,<4"

boto3 = "^1.28.76"
dateparser = "^1.2.0"

[tool.poetry.group.dev.dependencies]
moto = "^5.0.22"
pytest = "^8.3.4"
