SELECT
    C.NAME,
    TO_CHAR(G.BEGINNING_DATE_TIME AT TIME ZONE 'UTC', 'YYYYMMDD') AS YYYYMMDD,
    COUNT(DISTINCT G.CUMULUS_ID)                                  AS GRANULE_COUNT,
    COUNT(F.CUMULUS_ID)                                           AS FILE_COUNT
FROM
    PUBLIC.GRANULES G
        JOIN PUBLIC.COLLECTIONS C
             ON C.CUMULUS_ID = G.COLLECTION_CUMULUS_ID
        JOIN PUBLIC.FILES F
             ON F.GRANULE_CUMULUS_ID = G.CUMULUS_ID
                 AND F.CHECKSUM_VALUE IS NOT NULL
WHERE
      G.STATUS = 'completed'
  AND C.NAME = :'collection'
GROUP BY
    C.NAME,
    TO_CHAR(G.BEGINNING_DATE_TIME AT TIME ZONE 'UTC', 'YYYYMMDD')
ORDER BY
    C.NAME,
    TO_CHAR(G.BEGINNING_DATE_TIME AT TIME ZONE 'UTC', 'YYYYMMDD');
