[build-system]
requires = ["poetry-core~=2.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "remotezip-cli"
version = "0.3.0"
description = ""
license = "Apache-2.0"
authors = [
  { name = "Rohan Weeden", email = "reweeden@alaska.edu" },
]
readme = "README.md"
requires-python = "~=3.9"
dependencies = [
  "aws-requests-auth~=0.4.0",
  "boto3~=1.24",
  "humanize~=4.4",
  "remotezip~=0.9.0",
]

[tool.poetry]
packages = [{include = "remotezip_cli.py"}]

[project.scripts]
rz = "remotezip_cli:main"

[tool.poetry.group.dev.dependencies]
pytest = "~=8.3"
