[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "remotezip-cli"
version = "0.1.1"
description = ""
authors = ["Rohan Weeden <reweeden@alaska.edu>"]
readme = "README.md"
packages = [{include = "remotezip_cli.py"}]

[tool.poetry.scripts]
rz = "remotezip_cli:main"

[tool.poetry.dependencies]
python = ">=3.9,<4"
aws-requests-auth = "^0.4.3"
boto3 = "^1.24.76"
humanize = "^4.4.0"
remotezip = "^0.9.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
