[build-system]
requires = ["poetry-core~=2.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "cumulus-api"
version = "0.4.0"
description = ""
license = "Apache-2.0"
authors = [
  { name = "Rohan Weeden", email = "reweeden@alaska.edu" },
  { name = "Matt Perry", email = "mperry37@alaska.edu" },
]
readme = "README.md"
requires-python = "~=3.9"
dependencies = [
  "boto3~=1.28",
]

[project.optional-dependencies]
report = [
  "cumulus-report @ git+ssh://git@github.com:asfadmin/cumulus-report.git",
  "dateparser~=1.2",
  "sortedcontainers~=2.4",
]

[tool.poetry]
packages = [{include = "cumulus_api"}]

[project.scripts]
cumulus-api = "cumulus_api:main.main"
cumulus = "cumulus_api:main.main"
