[build-system]
requires = ["poetry-core~=2.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "destroy-cumulus"
version = "0.5.1"
description = ""
license = "Apache-2.0"
authors = [
  { name = "Rohan Weeden", email = "reweeden@alaska.edu" },
]
readme = "README.md"
requires-python = "~=3.9"
dependencies = [
  "boto3~=1.24",
]

[tool.poetry]
packages = [{include = "destroy_cumulus.py"}]

[project.scripts]
destroy-cumulus = "destroy_cumulus:main"
decumulus = "destroy_cumulus:main"

[tool.poetry.group.dev.dependencies]
moto = {extras = ["all"], version = "~=5.1"}
# openapi-schema-validator uses a private import from jsonpath and is therefore
# not compatible across all versions. 0.6.1 has a patch for an API change in
# jsonschema 4.19.1
# https://github.com/python-openapi/openapi-schema-validator/issues/131
openapi-schema-validator = ">=0.6.1"
pytest = "~=8.3"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
