[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "destroy-cumulus"
version = "0.4.0"
description = ""
license = "Apache-2.0"
authors = ["Rohan Weeden <reweeden@alaska.edu>"]
readme = "README.md"
packages = [{include = "destroy_cumulus.py"}]

[tool.poetry.scripts]
destroy-cumulus = "destroy_cumulus:main"
decumulus = "destroy_cumulus:main"

[tool.poetry.dependencies]
python = ">=3.9,<4"

boto3 = "^1.24.78"

[tool.poetry.group.dev.dependencies]
moto = {extras = ["all"], version = "^5.1.6"}
# openapi-schema-validator uses a private import from jsonpath and is therefore
# not compatible across all versions. 0.6.1 has a patch for an API change in
# jsonschema 4.19.1
# https://github.com/python-openapi/openapi-schema-validator/issues/131
openapi-schema-validator = ">=0.6.1"
pytest = "^8.3.4"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
