name: Lint

on:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: TrueBrain/actions-flake8@v2
        with:
          flake8_version: 7.3.0
          max_line_length: 120
          plugins: flake8-isort==7.0.0, flake8-quotes==3.4.0

  ruff-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: "~=0.15.13"
          args: format --check --diff --output-format=github
